### ISSUE TITLE
Similar module already on Packagist

### ISSUE THREAD

**Issue by yowcow** [Spomky-Labs/base64url#1]
Similar module already on [Packagist](https://packagist.org/packages/yowcow/mime-base64-urlsafe) with better tests.

**Comment by Spomky** [comment]
Thanks for the information.
This is a good news: the more there are similar open source projects, the more they are reliable. Thanks to shared experiences.

I let this issue open. I will add new tests later.

This is right, the library in reference seems to have better tests. But the library itself is not really fast and this is my goal.
I launched [a small benchmark](https://gist.github.com/Spomky/477b10577c3dae32968b) and here is the result:

    yowcow/mime-base64-urlsafe: 9.0428991317749 seconds
    spomky-labs/base64url: 5.8546080589294 seconds

IMO, this is because of the regex functions and the padding added when decoded.

Anyway, thanks again for your report.

**Comment by Spomky** [comment]
Tests added.
